In [116]:
import numpy as np
from functools import reduce
import operator as op

In [117]:
N = 64

In [118]:
np.random.randint(0, 2, N)

array([1, 1, 0, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1,
       1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0,
       1, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1])

In [119]:
bits = np.random.randint(0, 2, N)
bits

array([1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 1,
       1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 0,
       1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1])

In [120]:
print(bits.reshape(int(N**0.5),int(N**0.5)))

[[1 0 0 0 1 1 0 0]
 [1 0 0 1 0 1 0 0]
 [1 0 0 1 1 1 1 0]
 [0 1 1 0 0 0 0 0]
 [0 0 0 0 0 1 1 1]
 [1 1 1 0 1 1 1 1]
 [0 0 1 0 1 1 1 1]
 [1 0 0 1 0 0 1 1]]


In [121]:
s = 0
for i, bit in enumerate(bits):
    if bit == 1:
        s = s ^ i  
print(s)

39


In [124]:
p = reduce(lambda x, y: x ^ y, [i for i , bit in enumerate(bits) if bit])

In [123]:
# to make a well prepared block, need the xor sum to be zero
# make the parity bits correct

In [125]:
bits[p] = not bits[p]

In [126]:
flip = 12

In [127]:
bits[flip] = not bits[flip]

In [129]:
reduce(lambda x, y: x ^ y, [i for i , bit in enumerate(bits) if bit])

12

The Devil's Chessboard

https://chatgpt.com/share/677275de-5684-8003-ab36-f532055d22ad

In [155]:
N = 64
bits = np.random.randint(0, 2, N)
bits

array([1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0,
       0, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 1, 1, 0, 0, 0,
       0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0])

In [156]:
print(bits.reshape(int(N**0.5),int(N**0.5)))

[[1 1 0 0 0 0 0 0]
 [0 0 0 1 1 0 1 0]
 [1 1 0 0 0 0 0 1]
 [0 1 1 0 1 1 0 1]
 [0 0 1 0 1 1 0 1]
 [1 0 0 0 0 1 0 1]
 [0 1 0 1 0 0 0 0]
 [0 1 0 1 1 0 1 0]]


In [157]:
key = 25

In [158]:
xor_sum = reduce(lambda x, y: x ^ y, [i for i , bit in enumerate(bits) if bit])
xor_sum

47

In [159]:
#use the property of xor, the inverse of xor is itself

In [160]:
flip = xor_sum ^ key
flip

54

In [161]:
#key = flip ^ xor_sum
flip ^ xor_sum

25

we flip the "flip", because the prisoner2 can first calculate xor_sum, then figure out the key  
So, flipping a single position effectively adds or removes that square’s binary value from the XOR sum.

In [150]:
bits[flip] = not bits[flip]

In [152]:
#key's location
reduce(lambda x, y: x ^ y, [i for i , bit in enumerate(bits) if bit])

25

4x4

In [243]:
N = 16
bits = np.array([1, 0, 1, 0, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 0])
print(bits.reshape(int(N**0.5),int(N**0.5)))

[[1 0 1 0]
 [1 1 0 1]
 [0 1 0 1]
 [1 1 1 0]]


In [244]:
bits

array([1, 0, 1, 0, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 0])

In [245]:
xor_sum = reduce(lambda x, y: x ^ y, [i for i , bit in enumerate(bits) if bit])
xor_sum

9

In [246]:
key = 2

In [247]:
flip = xor_sum ^ key
flip

11

In [248]:
bits[flip] = not bits[flip]
print(bits.reshape(int(N**0.5),int(N**0.5)))

[[1 0 1 0]
 [1 1 0 1]
 [0 1 0 0]
 [1 1 1 0]]


In [252]:
xor_sum2 = reduce(lambda x, y: x ^ y, [i for i , bit in enumerate(bits) if bit])
xor_sum2

2

In [ ]:
# in this case 11 is fliped from 0 to 1
# thus
# xor_sum2 = xor_sum ^ 11
# and since flip = xor_sum ^ key = 11
# replace 11 with xor_sum ^ key
# xor_sum2 = xor_sum ^ (xor_sum ^ key) = key

In [253]:
N = 16
bits = np.array([1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 0])
print(bits.reshape(int(N**0.5),int(N**0.5)))

[[1 0 1 0]
 [1 1 1 1]
 [0 1 0 1]
 [1 1 1 0]]


In [254]:
bits

array([1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 0])

In [255]:
xor_sum = reduce(lambda x, y: x ^ y, [i for i , bit in enumerate(bits) if bit])
xor_sum

15

In [256]:
key = 2

In [257]:
flip = xor_sum ^ key
flip

13

In [258]:
bits[flip] = not bits[flip]
print(bits.reshape(int(N**0.5),int(N**0.5)))

[[1 0 1 0]
 [1 1 1 1]
 [0 1 0 1]
 [1 0 1 0]]


In [ ]:
xor_sum2 = reduce(lambda x, y: x ^ y, [i for i , bit in enumerate(bits) if bit])
xor_sum2

2

In [250]:
# in this case 13 is fliped from 1 to 0, 
# xor_sum2 should remove the 13 when doing xor sum, so we can cancel out 13 from xor_sum
# 13 = xor_sum ^ key
# xor_sum2 = xor_sum ^ (13)
# xor_sum2 = xor_sum ^ (xor_sum ^ key)
# xor_sum2 = key
